namespace Sushi_Time_PTC_2024.Vista.Administración_de_Empleados
{
    partial class AgregarUsuario
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AgregarUsuario));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.label1 = new System.Windows.Forms.Label();
            this.mskDUI = new System.Windows.Forms.MaskedTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel13 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel12 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel11 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel10 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel14 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel16 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel15 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.cmbCargo = new System.Windows.Forms.ComboBox();
            this.txtsalario = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnActualizar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.txtHijos = new Bunifu.UI.WinForms.BunifuTextBox();
            this.DPfechafinA = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.DPfechainicioA = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.label10 = new System.Windows.Forms.Label();
            this.dpNacimientoA = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.txtCorreoA = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtDireccionA = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtTelefonoA = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtCuentabA = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtApellidoA = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtnombreA = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtCodigoeA = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Agregar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(25, 99);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(198, 24);
            this.label1.TabIndex = 2;
            this.label1.Text = "Datos del Empleado";
            // 
            // mskDUI
            // 
            this.mskDUI.Location = new System.Drawing.Point(29, 349);
            this.mskDUI.Mask = "00000000-0";
            this.mskDUI.Name = "mskDUI";
            this.mskDUI.Size = new System.Drawing.Size(75, 20);
            this.mskDUI.TabIndex = 7;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Yu Gothic UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.Location = new System.Drawing.Point(178, 265);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(45, 20);
            this.bunifuLabel2.TabIndex = 121;
            this.bunifuLabel2.Text = "Correo";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel13
            // 
            this.bunifuLabel13.AllowParentOverrides = false;
            this.bunifuLabel13.AutoEllipsis = false;
            this.bunifuLabel13.CursorType = null;
            this.bunifuLabel13.Font = new System.Drawing.Font("Yu Gothic UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel13.Location = new System.Drawing.Point(23, 448);
            this.bunifuLabel13.Name = "bunifuLabel13";
            this.bunifuLabel13.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel13.Size = new System.Drawing.Size(63, 20);
            this.bunifuLabel13.TabIndex = 110;
            this.bunifuLabel13.Text = "Dirección";
            this.bunifuLabel13.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel13.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel12
            // 
            this.bunifuLabel12.AllowParentOverrides = false;
            this.bunifuLabel12.AutoEllipsis = false;
            this.bunifuLabel12.CursorType = null;
            this.bunifuLabel12.Font = new System.Drawing.Font("Yu Gothic UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel12.Location = new System.Drawing.Point(275, 205);
            this.bunifuLabel12.Name = "bunifuLabel12";
            this.bunifuLabel12.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel12.Size = new System.Drawing.Size(137, 20);
            this.bunifuLabel12.TabIndex = 109;
            this.bunifuLabel12.Text = "Cargo en la Empresa";
            this.bunifuLabel12.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel12.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel11
            // 
            this.bunifuLabel11.AllowParentOverrides = false;
            this.bunifuLabel11.AutoEllipsis = false;
            this.bunifuLabel11.CursorType = null;
            this.bunifuLabel11.Font = new System.Drawing.Font("Yu Gothic UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel11.Location = new System.Drawing.Point(29, 322);
            this.bunifuLabel11.Name = "bunifuLabel11";
            this.bunifuLabel11.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel11.Size = new System.Drawing.Size(40, 20);
            this.bunifuLabel11.TabIndex = 108;
            this.bunifuLabel11.Text = "N DUI";
            this.bunifuLabel11.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel11.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel10
            // 
            this.bunifuLabel10.AllowParentOverrides = false;
            this.bunifuLabel10.AutoEllipsis = false;
            this.bunifuLabel10.CursorType = null;
            this.bunifuLabel10.Font = new System.Drawing.Font("Yu Gothic UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel10.Location = new System.Drawing.Point(323, 143);
            this.bunifuLabel10.Name = "bunifuLabel10";
            this.bunifuLabel10.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel10.Size = new System.Drawing.Size(63, 20);
            this.bunifuLabel10.TabIndex = 107;
            this.bunifuLabel10.Text = "Apellidos";
            this.bunifuLabel10.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel10.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Yu Gothic UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel8.Location = new System.Drawing.Point(184, 330);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(46, 20);
            this.bunifuLabel8.TabIndex = 105;
            this.bunifuLabel8.Text = "Salario";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Yu Gothic UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel7.Location = new System.Drawing.Point(477, 265);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(74, 20);
            this.bunifuLabel7.TabIndex = 104;
            this.bunifuLabel7.Text = "N Telefono";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Yu Gothic UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.Location = new System.Drawing.Point(24, 143);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(61, 20);
            this.bunifuLabel6.TabIndex = 103;
            this.bunifuLabel6.Text = "Nombres";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Yu Gothic UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.Location = new System.Drawing.Point(23, 205);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(140, 20);
            this.bunifuLabel4.TabIndex = 101;
            this.bunifuLabel4.Text = "Fecha de Nacimiento";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Yu Gothic UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.Location = new System.Drawing.Point(476, 330);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(122, 20);
            this.bunifuLabel3.TabIndex = 100;
            this.bunifuLabel3.Text = "N Cuenta Bancaria";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel14
            // 
            this.bunifuLabel14.AllowParentOverrides = false;
            this.bunifuLabel14.AutoEllipsis = false;
            this.bunifuLabel14.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel14.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel14.Font = new System.Drawing.Font("Yu Gothic UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel14.Location = new System.Drawing.Point(466, 205);
            this.bunifuLabel14.Name = "bunifuLabel14";
            this.bunifuLabel14.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel14.Size = new System.Drawing.Size(146, 20);
            this.bunifuLabel14.TabIndex = 99;
            this.bunifuLabel14.Text = "Codigo del Empleado";
            this.bunifuLabel14.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel14.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel16
            // 
            this.bunifuLabel16.AllowParentOverrides = false;
            this.bunifuLabel16.AutoEllipsis = false;
            this.bunifuLabel16.CursorType = null;
            this.bunifuLabel16.Font = new System.Drawing.Font("Yu Gothic UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel16.Location = new System.Drawing.Point(347, 391);
            this.bunifuLabel16.Name = "bunifuLabel16";
            this.bunifuLabel16.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel16.Size = new System.Drawing.Size(141, 20);
            this.bunifuLabel16.TabIndex = 129;
            this.bunifuLabel16.Text = "Fecha de Finalizacion\r\n";
            this.bunifuLabel16.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel16.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel15
            // 
            this.bunifuLabel15.AllowParentOverrides = false;
            this.bunifuLabel15.AutoEllipsis = false;
            this.bunifuLabel15.CursorType = null;
            this.bunifuLabel15.Font = new System.Drawing.Font("Yu Gothic UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel15.Location = new System.Drawing.Point(24, 391);
            this.bunifuLabel15.Name = "bunifuLabel15";
            this.bunifuLabel15.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel15.Size = new System.Drawing.Size(99, 20);
            this.bunifuLabel15.TabIndex = 128;
            this.bunifuLabel15.Text = "Fecha de Inicio";
            this.bunifuLabel15.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel15.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Yu Gothic UI", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.Location = new System.Drawing.Point(25, 265);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(34, 20);
            this.bunifuLabel1.TabIndex = 130;
            this.bunifuLabel1.Text = "Hijos";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // cmbCargo
            // 
            this.cmbCargo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbCargo.FormattingEnabled = true;
            this.cmbCargo.Location = new System.Drawing.Point(275, 231);
            this.cmbCargo.Name = "cmbCargo";
            this.cmbCargo.Size = new System.Drawing.Size(160, 21);
            this.cmbCargo.TabIndex = 2;
            // 
            // txtsalario
            // 
            this.txtsalario.AcceptsReturn = false;
            this.txtsalario.AcceptsTab = false;
            this.txtsalario.AnimationSpeed = 200;
            this.txtsalario.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtsalario.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtsalario.AutoSizeHeight = true;
            this.txtsalario.BackColor = System.Drawing.Color.Transparent;
            this.txtsalario.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtsalario.BackgroundImage")));
            this.txtsalario.BorderColorActive = System.Drawing.Color.Black;
            this.txtsalario.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtsalario.BorderColorHover = System.Drawing.Color.Black;
            this.txtsalario.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtsalario.BorderRadius = 1;
            this.txtsalario.BorderThickness = 1;
            this.txtsalario.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtsalario.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtsalario.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtsalario.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtsalario.DefaultText = "";
            this.txtsalario.FillColor = System.Drawing.Color.White;
            this.txtsalario.HideSelection = true;
            this.txtsalario.IconLeft = null;
            this.txtsalario.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtsalario.IconPadding = 10;
            this.txtsalario.IconRight = null;
            this.txtsalario.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtsalario.Lines = new string[0];
            this.txtsalario.Location = new System.Drawing.Point(184, 349);
            this.txtsalario.MaxLength = 32767;
            this.txtsalario.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtsalario.Modified = false;
            this.txtsalario.Multiline = false;
            this.txtsalario.Name = "txtsalario";
            stateProperties1.BorderColor = System.Drawing.Color.Black;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtsalario.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtsalario.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.Black;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtsalario.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtsalario.OnIdleState = stateProperties4;
            this.txtsalario.Padding = new System.Windows.Forms.Padding(3);
            this.txtsalario.PasswordChar = '\0';
            this.txtsalario.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtsalario.PlaceholderText = "";
            this.txtsalario.ReadOnly = false;
            this.txtsalario.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtsalario.SelectedText = "";
            this.txtsalario.SelectionLength = 0;
            this.txtsalario.SelectionStart = 0;
            this.txtsalario.ShortcutsEnabled = true;
            this.txtsalario.Size = new System.Drawing.Size(137, 24);
            this.txtsalario.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtsalario.TabIndex = 8;
            this.txtsalario.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtsalario.TextMarginBottom = 0;
            this.txtsalario.TextMarginLeft = 3;
            this.txtsalario.TextMarginTop = 1;
            this.txtsalario.TextPlaceholder = "";
            this.txtsalario.UseSystemPasswordChar = false;
            this.txtsalario.WordWrap = true;
            // 
            // btnActualizar
            // 
            this.btnActualizar.AllowAnimations = true;
            this.btnActualizar.AllowMouseEffects = true;
            this.btnActualizar.AllowToggling = false;
            this.btnActualizar.AnimationSpeed = 200;
            this.btnActualizar.AutoGenerateColors = false;
            this.btnActualizar.AutoRoundBorders = false;
            this.btnActualizar.AutoSizeLeftIcon = true;
            this.btnActualizar.AutoSizeRightIcon = true;
            this.btnActualizar.BackColor = System.Drawing.Color.Transparent;
            this.btnActualizar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(197)))), ((int)(((byte)(18)))), ((int)(((byte)(48)))));
            this.btnActualizar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnActualizar.BackgroundImage")));
            this.btnActualizar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnActualizar.ButtonText = "Actualizar";
            this.btnActualizar.ButtonTextMarginLeft = 0;
            this.btnActualizar.ColorContrastOnClick = 45;
            this.btnActualizar.ColorContrastOnHover = 45;
            this.btnActualizar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnActualizar.CustomizableEdges = borderEdges1;
            this.btnActualizar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnActualizar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnActualizar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnActualizar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnActualizar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnActualizar.Font = new System.Drawing.Font("Yu Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnActualizar.ForeColor = System.Drawing.Color.White;
            this.btnActualizar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnActualizar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnActualizar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnActualizar.IconMarginLeft = 11;
            this.btnActualizar.IconPadding = 10;
            this.btnActualizar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnActualizar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnActualizar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnActualizar.IconSize = 25;
            this.btnActualizar.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnActualizar.IdleBorderRadius = 20;
            this.btnActualizar.IdleBorderThickness = 1;
            this.btnActualizar.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(197)))), ((int)(((byte)(18)))), ((int)(((byte)(48)))));
            this.btnActualizar.IdleIconLeftImage = null;
            this.btnActualizar.IdleIconRightImage = null;
            this.btnActualizar.IndicateFocus = false;
            this.btnActualizar.Location = new System.Drawing.Point(466, 89);
            this.btnActualizar.Name = "btnActualizar";
            this.btnActualizar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnActualizar.OnDisabledState.BorderRadius = 20;
            this.btnActualizar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnActualizar.OnDisabledState.BorderThickness = 1;
            this.btnActualizar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnActualizar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnActualizar.OnDisabledState.IconLeftImage = null;
            this.btnActualizar.OnDisabledState.IconRightImage = null;
            this.btnActualizar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnActualizar.onHoverState.BorderRadius = 20;
            this.btnActualizar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnActualizar.onHoverState.BorderThickness = 1;
            this.btnActualizar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnActualizar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnActualizar.onHoverState.IconLeftImage = null;
            this.btnActualizar.onHoverState.IconRightImage = null;
            this.btnActualizar.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnActualizar.OnIdleState.BorderRadius = 20;
            this.btnActualizar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnActualizar.OnIdleState.BorderThickness = 1;
            this.btnActualizar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(197)))), ((int)(((byte)(18)))), ((int)(((byte)(48)))));
            this.btnActualizar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnActualizar.OnIdleState.IconLeftImage = null;
            this.btnActualizar.OnIdleState.IconRightImage = null;
            this.btnActualizar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnActualizar.OnPressedState.BorderRadius = 20;
            this.btnActualizar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnActualizar.OnPressedState.BorderThickness = 1;
            this.btnActualizar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnActualizar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnActualizar.OnPressedState.IconLeftImage = null;
            this.btnActualizar.OnPressedState.IconRightImage = null;
            this.btnActualizar.Size = new System.Drawing.Size(68, 32);
            this.btnActualizar.TabIndex = 132;
            this.btnActualizar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnActualizar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnActualizar.TextMarginLeft = 0;
            this.btnActualizar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnActualizar.UseDefaultRadiusAndThickness = true;
            // 
            // txtHijos
            // 
            this.txtHijos.AcceptsReturn = false;
            this.txtHijos.AcceptsTab = false;
            this.txtHijos.AnimationSpeed = 200;
            this.txtHijos.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtHijos.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtHijos.AutoSizeHeight = true;
            this.txtHijos.BackColor = System.Drawing.Color.Transparent;
            this.txtHijos.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtHijos.BackgroundImage")));
            this.txtHijos.BorderColorActive = System.Drawing.Color.Black;
            this.txtHijos.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtHijos.BorderColorHover = System.Drawing.Color.Black;
            this.txtHijos.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtHijos.BorderRadius = 1;
            this.txtHijos.BorderThickness = 1;
            this.txtHijos.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtHijos.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtHijos.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtHijos.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtHijos.DefaultText = "";
            this.txtHijos.FillColor = System.Drawing.Color.White;
            this.txtHijos.HideSelection = true;
            this.txtHijos.IconLeft = null;
            this.txtHijos.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtHijos.IconPadding = 10;
            this.txtHijos.IconRight = null;
            this.txtHijos.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtHijos.Lines = new string[0];
            this.txtHijos.Location = new System.Drawing.Point(26, 288);
            this.txtHijos.MaxLength = 2;
            this.txtHijos.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtHijos.Modified = false;
            this.txtHijos.Multiline = false;
            this.txtHijos.Name = "txtHijos";
            stateProperties5.BorderColor = System.Drawing.Color.Black;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtHijos.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtHijos.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.Black;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtHijos.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtHijos.OnIdleState = stateProperties8;
            this.txtHijos.Padding = new System.Windows.Forms.Padding(3);
            this.txtHijos.PasswordChar = '\0';
            this.txtHijos.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtHijos.PlaceholderText = "";
            this.txtHijos.ReadOnly = false;
            this.txtHijos.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtHijos.SelectedText = "";
            this.txtHijos.SelectionLength = 0;
            this.txtHijos.SelectionStart = 0;
            this.txtHijos.ShortcutsEnabled = true;
            this.txtHijos.Size = new System.Drawing.Size(137, 24);
            this.txtHijos.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtHijos.TabIndex = 4;
            this.txtHijos.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtHijos.TextMarginBottom = 0;
            this.txtHijos.TextMarginLeft = 3;
            this.txtHijos.TextMarginTop = 1;
            this.txtHijos.TextPlaceholder = "";
            this.txtHijos.UseSystemPasswordChar = false;
            this.txtHijos.WordWrap = true;
            // 
            // DPfechafinA
            // 
            this.DPfechafinA.BackColor = System.Drawing.Color.Transparent;
            this.DPfechafinA.BorderColor = System.Drawing.Color.Silver;
            this.DPfechafinA.BorderRadius = 1;
            this.DPfechafinA.Color = System.Drawing.Color.Silver;
            this.DPfechafinA.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.DPfechafinA.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.DPfechafinA.DisabledColor = System.Drawing.Color.Gray;
            this.DPfechafinA.DisplayWeekNumbers = false;
            this.DPfechafinA.DPHeight = 0;
            this.DPfechafinA.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.DPfechafinA.FillDatePicker = false;
            this.DPfechafinA.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.DPfechafinA.ForeColor = System.Drawing.Color.Black;
            this.DPfechafinA.Icon = ((System.Drawing.Image)(resources.GetObject("DPfechafinA.Icon")));
            this.DPfechafinA.IconColor = System.Drawing.Color.Gray;
            this.DPfechafinA.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.DPfechafinA.LeftTextMargin = 5;
            this.DPfechafinA.Location = new System.Drawing.Point(319, 417);
            this.DPfechafinA.MinimumSize = new System.Drawing.Size(4, 32);
            this.DPfechafinA.Name = "DPfechafinA";
            this.DPfechafinA.Size = new System.Drawing.Size(232, 32);
            this.DPfechafinA.TabIndex = 14;
            // 
            // DPfechainicioA
            // 
            this.DPfechainicioA.BackColor = System.Drawing.Color.Transparent;
            this.DPfechainicioA.BorderColor = System.Drawing.Color.Silver;
            this.DPfechainicioA.BorderRadius = 1;
            this.DPfechainicioA.Color = System.Drawing.Color.Silver;
            this.DPfechainicioA.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.DPfechainicioA.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.DPfechainicioA.DisabledColor = System.Drawing.Color.Gray;
            this.DPfechainicioA.DisplayWeekNumbers = false;
            this.DPfechainicioA.DPHeight = 0;
            this.DPfechainicioA.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.DPfechainicioA.FillDatePicker = false;
            this.DPfechainicioA.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.DPfechainicioA.ForeColor = System.Drawing.Color.Black;
            this.DPfechainicioA.Icon = ((System.Drawing.Image)(resources.GetObject("DPfechainicioA.Icon")));
            this.DPfechainicioA.IconColor = System.Drawing.Color.Gray;
            this.DPfechainicioA.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.DPfechainicioA.LeftTextMargin = 5;
            this.DPfechainicioA.Location = new System.Drawing.Point(24, 417);
            this.DPfechainicioA.MinimumSize = new System.Drawing.Size(4, 32);
            this.DPfechainicioA.Name = "DPfechainicioA";
            this.DPfechainicioA.Size = new System.Drawing.Size(226, 32);
            this.DPfechainicioA.TabIndex = 13;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.label10);
            this.bunifuPanel1.Location = new System.Drawing.Point(-4, -6);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(655, 86);
            this.bunifuPanel1.TabIndex = 125;
            this.bunifuPanel1.TabStop = true;
            // 
            // label10
            // 
            this.label10.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.label10.AutoSize = true;
            this.label10.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.label10.Font = new System.Drawing.Font("MS Reference Sans Serif", 20.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label10.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label10.Location = new System.Drawing.Point(182, 12);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(285, 68);
            this.label10.TabIndex = 37;
            this.label10.Text = "Administración de \r\nempleados";
            this.label10.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // dpNacimientoA
            // 
            this.dpNacimientoA.BackColor = System.Drawing.Color.Transparent;
            this.dpNacimientoA.BorderColor = System.Drawing.Color.Silver;
            this.dpNacimientoA.BorderRadius = 1;
            this.dpNacimientoA.Color = System.Drawing.Color.Silver;
            this.dpNacimientoA.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dpNacimientoA.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dpNacimientoA.DisabledColor = System.Drawing.Color.Gray;
            this.dpNacimientoA.DisplayWeekNumbers = false;
            this.dpNacimientoA.DPHeight = 0;
            this.dpNacimientoA.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.dpNacimientoA.FillDatePicker = false;
            this.dpNacimientoA.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.dpNacimientoA.ForeColor = System.Drawing.Color.Black;
            this.dpNacimientoA.Icon = ((System.Drawing.Image)(resources.GetObject("dpNacimientoA.Icon")));
            this.dpNacimientoA.IconColor = System.Drawing.Color.Gray;
            this.dpNacimientoA.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dpNacimientoA.LeftTextMargin = 5;
            this.dpNacimientoA.Location = new System.Drawing.Point(20, 226);
            this.dpNacimientoA.MinimumSize = new System.Drawing.Size(4, 32);
            this.dpNacimientoA.Name = "dpNacimientoA";
            this.dpNacimientoA.Size = new System.Drawing.Size(230, 32);
            this.dpNacimientoA.TabIndex = 8;
            // 
            // txtCorreoA
            // 
            this.txtCorreoA.AcceptsReturn = false;
            this.txtCorreoA.AcceptsTab = false;
            this.txtCorreoA.AnimationSpeed = 200;
            this.txtCorreoA.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCorreoA.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCorreoA.AutoSizeHeight = true;
            this.txtCorreoA.BackColor = System.Drawing.Color.Transparent;
            this.txtCorreoA.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCorreoA.BackgroundImage")));
            this.txtCorreoA.BorderColorActive = System.Drawing.Color.Black;
            this.txtCorreoA.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCorreoA.BorderColorHover = System.Drawing.Color.Black;
            this.txtCorreoA.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCorreoA.BorderRadius = 1;
            this.txtCorreoA.BorderThickness = 1;
            this.txtCorreoA.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCorreoA.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCorreoA.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCorreoA.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCorreoA.DefaultText = "";
            this.txtCorreoA.FillColor = System.Drawing.Color.White;
            this.txtCorreoA.HideSelection = true;
            this.txtCorreoA.IconLeft = null;
            this.txtCorreoA.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCorreoA.IconPadding = 10;
            this.txtCorreoA.IconRight = null;
            this.txtCorreoA.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCorreoA.Lines = new string[0];
            this.txtCorreoA.Location = new System.Drawing.Point(178, 288);
            this.txtCorreoA.MaxLength = 50;
            this.txtCorreoA.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCorreoA.Modified = false;
            this.txtCorreoA.Multiline = false;
            this.txtCorreoA.Name = "txtCorreoA";
            stateProperties9.BorderColor = System.Drawing.Color.Black;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCorreoA.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCorreoA.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.Black;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCorreoA.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCorreoA.OnIdleState = stateProperties12;
            this.txtCorreoA.Padding = new System.Windows.Forms.Padding(3);
            this.txtCorreoA.PasswordChar = '\0';
            this.txtCorreoA.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCorreoA.PlaceholderText = "";
            this.txtCorreoA.ReadOnly = false;
            this.txtCorreoA.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCorreoA.SelectedText = "";
            this.txtCorreoA.SelectionLength = 0;
            this.txtCorreoA.SelectionStart = 0;
            this.txtCorreoA.ShortcutsEnabled = true;
            this.txtCorreoA.Size = new System.Drawing.Size(285, 24);
            this.txtCorreoA.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCorreoA.TabIndex = 5;
            this.txtCorreoA.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCorreoA.TextMarginBottom = 0;
            this.txtCorreoA.TextMarginLeft = 3;
            this.txtCorreoA.TextMarginTop = 1;
            this.txtCorreoA.TextPlaceholder = "";
            this.txtCorreoA.UseSystemPasswordChar = false;
            this.txtCorreoA.WordWrap = true;
            // 
            // txtDireccionA
            // 
            this.txtDireccionA.AcceptsReturn = false;
            this.txtDireccionA.AcceptsTab = false;
            this.txtDireccionA.AnimationSpeed = 200;
            this.txtDireccionA.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDireccionA.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDireccionA.AutoSizeHeight = true;
            this.txtDireccionA.BackColor = System.Drawing.Color.Transparent;
            this.txtDireccionA.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDireccionA.BackgroundImage")));
            this.txtDireccionA.BorderColorActive = System.Drawing.Color.Black;
            this.txtDireccionA.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDireccionA.BorderColorHover = System.Drawing.Color.Black;
            this.txtDireccionA.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDireccionA.BorderRadius = 1;
            this.txtDireccionA.BorderThickness = 1;
            this.txtDireccionA.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtDireccionA.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDireccionA.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDireccionA.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDireccionA.DefaultText = "";
            this.txtDireccionA.FillColor = System.Drawing.Color.White;
            this.txtDireccionA.HideSelection = true;
            this.txtDireccionA.IconLeft = null;
            this.txtDireccionA.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDireccionA.IconPadding = 10;
            this.txtDireccionA.IconRight = null;
            this.txtDireccionA.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDireccionA.Lines = new string[0];
            this.txtDireccionA.Location = new System.Drawing.Point(20, 477);
            this.txtDireccionA.MaxLength = 1000;
            this.txtDireccionA.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDireccionA.Modified = false;
            this.txtDireccionA.Multiline = true;
            this.txtDireccionA.Name = "txtDireccionA";
            stateProperties13.BorderColor = System.Drawing.Color.Black;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDireccionA.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDireccionA.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.Black;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDireccionA.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDireccionA.OnIdleState = stateProperties16;
            this.txtDireccionA.Padding = new System.Windows.Forms.Padding(3);
            this.txtDireccionA.PasswordChar = '\0';
            this.txtDireccionA.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDireccionA.PlaceholderText = "";
            this.txtDireccionA.ReadOnly = false;
            this.txtDireccionA.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDireccionA.SelectedText = "";
            this.txtDireccionA.SelectionLength = 0;
            this.txtDireccionA.SelectionStart = 0;
            this.txtDireccionA.ShortcutsEnabled = true;
            this.txtDireccionA.Size = new System.Drawing.Size(614, 94);
            this.txtDireccionA.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDireccionA.TabIndex = 9;
            this.txtDireccionA.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDireccionA.TextMarginBottom = 0;
            this.txtDireccionA.TextMarginLeft = 3;
            this.txtDireccionA.TextMarginTop = 1;
            this.txtDireccionA.TextPlaceholder = "";
            this.txtDireccionA.UseSystemPasswordChar = false;
            this.txtDireccionA.WordWrap = true;
            // 
            // txtTelefonoA
            // 
            this.txtTelefonoA.AcceptsReturn = false;
            this.txtTelefonoA.AcceptsTab = false;
            this.txtTelefonoA.AnimationSpeed = 200;
            this.txtTelefonoA.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTelefonoA.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTelefonoA.AutoSizeHeight = true;
            this.txtTelefonoA.BackColor = System.Drawing.Color.Transparent;
            this.txtTelefonoA.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTelefonoA.BackgroundImage")));
            this.txtTelefonoA.BorderColorActive = System.Drawing.Color.Black;
            this.txtTelefonoA.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTelefonoA.BorderColorHover = System.Drawing.Color.Black;
            this.txtTelefonoA.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTelefonoA.BorderRadius = 1;
            this.txtTelefonoA.BorderThickness = 1;
            this.txtTelefonoA.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtTelefonoA.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTelefonoA.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefonoA.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtTelefonoA.DefaultText = "";
            this.txtTelefonoA.FillColor = System.Drawing.Color.White;
            this.txtTelefonoA.HideSelection = true;
            this.txtTelefonoA.IconLeft = null;
            this.txtTelefonoA.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefonoA.IconPadding = 10;
            this.txtTelefonoA.IconRight = null;
            this.txtTelefonoA.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTelefonoA.Lines = new string[0];
            this.txtTelefonoA.Location = new System.Drawing.Point(476, 288);
            this.txtTelefonoA.MaxLength = 8;
            this.txtTelefonoA.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTelefonoA.Modified = false;
            this.txtTelefonoA.Multiline = false;
            this.txtTelefonoA.Name = "txtTelefonoA";
            stateProperties17.BorderColor = System.Drawing.Color.Black;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefonoA.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTelefonoA.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.Black;
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefonoA.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTelefonoA.OnIdleState = stateProperties20;
            this.txtTelefonoA.Padding = new System.Windows.Forms.Padding(3);
            this.txtTelefonoA.PasswordChar = '\0';
            this.txtTelefonoA.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTelefonoA.PlaceholderText = "";
            this.txtTelefonoA.ReadOnly = false;
            this.txtTelefonoA.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTelefonoA.SelectedText = "";
            this.txtTelefonoA.SelectionLength = 0;
            this.txtTelefonoA.SelectionStart = 0;
            this.txtTelefonoA.ShortcutsEnabled = true;
            this.txtTelefonoA.Size = new System.Drawing.Size(137, 24);
            this.txtTelefonoA.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTelefonoA.TabIndex = 6;
            this.txtTelefonoA.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTelefonoA.TextMarginBottom = 0;
            this.txtTelefonoA.TextMarginLeft = 3;
            this.txtTelefonoA.TextMarginTop = 1;
            this.txtTelefonoA.TextPlaceholder = "";
            this.txtTelefonoA.UseSystemPasswordChar = false;
            this.txtTelefonoA.WordWrap = true;
            this.txtTelefonoA.TextChanged += new System.EventHandler(this.bunifuTextBox5_TextChanged);
            // 
            // txtCuentabA
            // 
            this.txtCuentabA.AcceptsReturn = false;
            this.txtCuentabA.AcceptsTab = false;
            this.txtCuentabA.AnimationSpeed = 200;
            this.txtCuentabA.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCuentabA.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCuentabA.AutoSizeHeight = true;
            this.txtCuentabA.BackColor = System.Drawing.Color.Transparent;
            this.txtCuentabA.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCuentabA.BackgroundImage")));
            this.txtCuentabA.BorderColorActive = System.Drawing.Color.Black;
            this.txtCuentabA.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCuentabA.BorderColorHover = System.Drawing.Color.Black;
            this.txtCuentabA.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCuentabA.BorderRadius = 1;
            this.txtCuentabA.BorderThickness = 1;
            this.txtCuentabA.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCuentabA.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCuentabA.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCuentabA.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCuentabA.DefaultText = "";
            this.txtCuentabA.FillColor = System.Drawing.Color.White;
            this.txtCuentabA.HideSelection = true;
            this.txtCuentabA.IconLeft = null;
            this.txtCuentabA.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCuentabA.IconPadding = 10;
            this.txtCuentabA.IconRight = null;
            this.txtCuentabA.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCuentabA.Lines = new string[0];
            this.txtCuentabA.Location = new System.Drawing.Point(476, 356);
            this.txtCuentabA.MaxLength = 20;
            this.txtCuentabA.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCuentabA.Modified = false;
            this.txtCuentabA.Multiline = false;
            this.txtCuentabA.Name = "txtCuentabA";
            stateProperties21.BorderColor = System.Drawing.Color.Black;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCuentabA.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCuentabA.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.Black;
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCuentabA.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCuentabA.OnIdleState = stateProperties24;
            this.txtCuentabA.Padding = new System.Windows.Forms.Padding(3);
            this.txtCuentabA.PasswordChar = '\0';
            this.txtCuentabA.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCuentabA.PlaceholderText = "";
            this.txtCuentabA.ReadOnly = false;
            this.txtCuentabA.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCuentabA.SelectedText = "";
            this.txtCuentabA.SelectionLength = 0;
            this.txtCuentabA.SelectionStart = 0;
            this.txtCuentabA.ShortcutsEnabled = true;
            this.txtCuentabA.Size = new System.Drawing.Size(137, 25);
            this.txtCuentabA.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCuentabA.TabIndex = 9;
            this.txtCuentabA.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCuentabA.TextMarginBottom = 0;
            this.txtCuentabA.TextMarginLeft = 3;
            this.txtCuentabA.TextMarginTop = 1;
            this.txtCuentabA.TextPlaceholder = "";
            this.txtCuentabA.UseSystemPasswordChar = false;
            this.txtCuentabA.WordWrap = true;
            // 
            // txtApellidoA
            // 
            this.txtApellidoA.AcceptsReturn = false;
            this.txtApellidoA.AcceptsTab = false;
            this.txtApellidoA.AnimationSpeed = 200;
            this.txtApellidoA.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtApellidoA.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtApellidoA.AutoSizeHeight = true;
            this.txtApellidoA.BackColor = System.Drawing.Color.Transparent;
            this.txtApellidoA.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtApellidoA.BackgroundImage")));
            this.txtApellidoA.BorderColorActive = System.Drawing.Color.Black;
            this.txtApellidoA.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtApellidoA.BorderColorHover = System.Drawing.Color.Black;
            this.txtApellidoA.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtApellidoA.BorderRadius = 1;
            this.txtApellidoA.BorderThickness = 1;
            this.txtApellidoA.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtApellidoA.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtApellidoA.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtApellidoA.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtApellidoA.DefaultText = "";
            this.txtApellidoA.FillColor = System.Drawing.Color.White;
            this.txtApellidoA.HideSelection = true;
            this.txtApellidoA.IconLeft = null;
            this.txtApellidoA.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtApellidoA.IconPadding = 10;
            this.txtApellidoA.IconRight = null;
            this.txtApellidoA.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtApellidoA.Lines = new string[0];
            this.txtApellidoA.Location = new System.Drawing.Point(320, 164);
            this.txtApellidoA.MaxLength = 50;
            this.txtApellidoA.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtApellidoA.Modified = false;
            this.txtApellidoA.Multiline = false;
            this.txtApellidoA.Name = "txtApellidoA";
            stateProperties25.BorderColor = System.Drawing.Color.Black;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtApellidoA.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtApellidoA.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.Black;
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtApellidoA.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtApellidoA.OnIdleState = stateProperties28;
            this.txtApellidoA.Padding = new System.Windows.Forms.Padding(3);
            this.txtApellidoA.PasswordChar = '\0';
            this.txtApellidoA.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtApellidoA.PlaceholderText = "";
            this.txtApellidoA.ReadOnly = false;
            this.txtApellidoA.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtApellidoA.SelectedText = "";
            this.txtApellidoA.SelectionLength = 0;
            this.txtApellidoA.SelectionStart = 0;
            this.txtApellidoA.ShortcutsEnabled = true;
            this.txtApellidoA.Size = new System.Drawing.Size(293, 24);
            this.txtApellidoA.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtApellidoA.TabIndex = 1;
            this.txtApellidoA.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtApellidoA.TextMarginBottom = 0;
            this.txtApellidoA.TextMarginLeft = 3;
            this.txtApellidoA.TextMarginTop = 1;
            this.txtApellidoA.TextPlaceholder = "";
            this.txtApellidoA.UseSystemPasswordChar = false;
            this.txtApellidoA.WordWrap = true;
            // 
            // txtnombreA
            // 
            this.txtnombreA.AcceptsReturn = false;
            this.txtnombreA.AcceptsTab = false;
            this.txtnombreA.AnimationSpeed = 200;
            this.txtnombreA.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtnombreA.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtnombreA.AutoSizeHeight = true;
            this.txtnombreA.BackColor = System.Drawing.Color.Transparent;
            this.txtnombreA.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtnombreA.BackgroundImage")));
            this.txtnombreA.BorderColorActive = System.Drawing.Color.Black;
            this.txtnombreA.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtnombreA.BorderColorHover = System.Drawing.Color.Black;
            this.txtnombreA.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtnombreA.BorderRadius = 1;
            this.txtnombreA.BorderThickness = 1;
            this.txtnombreA.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtnombreA.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtnombreA.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtnombreA.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtnombreA.DefaultText = "";
            this.txtnombreA.FillColor = System.Drawing.Color.White;
            this.txtnombreA.HideSelection = true;
            this.txtnombreA.IconLeft = null;
            this.txtnombreA.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtnombreA.IconPadding = 10;
            this.txtnombreA.IconRight = null;
            this.txtnombreA.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtnombreA.Lines = new string[0];
            this.txtnombreA.Location = new System.Drawing.Point(24, 164);
            this.txtnombreA.MaxLength = 50;
            this.txtnombreA.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtnombreA.Modified = false;
            this.txtnombreA.Multiline = false;
            this.txtnombreA.Name = "txtnombreA";
            stateProperties29.BorderColor = System.Drawing.Color.Black;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtnombreA.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtnombreA.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.Black;
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtnombreA.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtnombreA.OnIdleState = stateProperties32;
            this.txtnombreA.Padding = new System.Windows.Forms.Padding(3);
            this.txtnombreA.PasswordChar = '\0';
            this.txtnombreA.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtnombreA.PlaceholderText = "";
            this.txtnombreA.ReadOnly = false;
            this.txtnombreA.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtnombreA.SelectedText = "";
            this.txtnombreA.SelectionLength = 0;
            this.txtnombreA.SelectionStart = 0;
            this.txtnombreA.ShortcutsEnabled = true;
            this.txtnombreA.Size = new System.Drawing.Size(286, 24);
            this.txtnombreA.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtnombreA.TabIndex = 0;
            this.txtnombreA.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtnombreA.TextMarginBottom = 0;
            this.txtnombreA.TextMarginLeft = 3;
            this.txtnombreA.TextMarginTop = 1;
            this.txtnombreA.TextPlaceholder = "";
            this.txtnombreA.UseSystemPasswordChar = false;
            this.txtnombreA.WordWrap = true;
            // 
            // txtCodigoeA
            // 
            this.txtCodigoeA.AcceptsReturn = false;
            this.txtCodigoeA.AcceptsTab = false;
            this.txtCodigoeA.AnimationSpeed = 200;
            this.txtCodigoeA.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCodigoeA.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCodigoeA.AutoSizeHeight = true;
            this.txtCodigoeA.BackColor = System.Drawing.Color.Transparent;
            this.txtCodigoeA.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCodigoeA.BackgroundImage")));
            this.txtCodigoeA.BorderColorActive = System.Drawing.Color.Black;
            this.txtCodigoeA.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCodigoeA.BorderColorHover = System.Drawing.Color.Black;
            this.txtCodigoeA.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtCodigoeA.BorderRadius = 1;
            this.txtCodigoeA.BorderThickness = 1;
            this.txtCodigoeA.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCodigoeA.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCodigoeA.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCodigoeA.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCodigoeA.DefaultText = "";
            this.txtCodigoeA.FillColor = System.Drawing.Color.White;
            this.txtCodigoeA.HideSelection = true;
            this.txtCodigoeA.IconLeft = null;
            this.txtCodigoeA.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCodigoeA.IconPadding = 10;
            this.txtCodigoeA.IconRight = null;
            this.txtCodigoeA.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCodigoeA.Lines = new string[0];
            this.txtCodigoeA.Location = new System.Drawing.Point(466, 226);
            this.txtCodigoeA.MaxLength = 32767;
            this.txtCodigoeA.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCodigoeA.Modified = false;
            this.txtCodigoeA.Multiline = false;
            this.txtCodigoeA.Name = "txtCodigoeA";
            stateProperties33.BorderColor = System.Drawing.Color.Black;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCodigoeA.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCodigoeA.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.Black;
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCodigoeA.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCodigoeA.OnIdleState = stateProperties36;
            this.txtCodigoeA.Padding = new System.Windows.Forms.Padding(3);
            this.txtCodigoeA.PasswordChar = '\0';
            this.txtCodigoeA.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCodigoeA.PlaceholderText = "";
            this.txtCodigoeA.ReadOnly = false;
            this.txtCodigoeA.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCodigoeA.SelectedText = "";
            this.txtCodigoeA.SelectionLength = 0;
            this.txtCodigoeA.SelectionStart = 0;
            this.txtCodigoeA.ShortcutsEnabled = true;
            this.txtCodigoeA.Size = new System.Drawing.Size(147, 24);
            this.txtCodigoeA.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCodigoeA.TabIndex = 3;
            this.txtCodigoeA.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCodigoeA.TextMarginBottom = 0;
            this.txtCodigoeA.TextMarginLeft = 3;
            this.txtCodigoeA.TextMarginTop = 1;
            this.txtCodigoeA.TextPlaceholder = "";
            this.txtCodigoeA.UseSystemPasswordChar = false;
            this.txtCodigoeA.WordWrap = true;
            // 
            // Agregar
            // 
            this.Agregar.AllowAnimations = true;
            this.Agregar.AllowMouseEffects = true;
            this.Agregar.AllowToggling = false;
            this.Agregar.AnimationSpeed = 200;
            this.Agregar.AutoGenerateColors = false;
            this.Agregar.AutoRoundBorders = false;
            this.Agregar.AutoSizeLeftIcon = true;
            this.Agregar.AutoSizeRightIcon = true;
            this.Agregar.BackColor = System.Drawing.Color.Transparent;
            this.Agregar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(197)))), ((int)(((byte)(18)))), ((int)(((byte)(48)))));
            this.Agregar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Agregar.BackgroundImage")));
            this.Agregar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Agregar.ButtonText = "Agregar";
            this.Agregar.ButtonTextMarginLeft = 0;
            this.Agregar.ColorContrastOnClick = 45;
            this.Agregar.ColorContrastOnHover = 45;
            this.Agregar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.Agregar.CustomizableEdges = borderEdges2;
            this.Agregar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Agregar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Agregar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Agregar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Agregar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.Agregar.Font = new System.Drawing.Font("Yu Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Agregar.ForeColor = System.Drawing.Color.White;
            this.Agregar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Agregar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Agregar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Agregar.IconMarginLeft = 11;
            this.Agregar.IconPadding = 10;
            this.Agregar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Agregar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Agregar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Agregar.IconSize = 25;
            this.Agregar.IdleBorderColor = System.Drawing.Color.Transparent;
            this.Agregar.IdleBorderRadius = 20;
            this.Agregar.IdleBorderThickness = 1;
            this.Agregar.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(197)))), ((int)(((byte)(18)))), ((int)(((byte)(48)))));
            this.Agregar.IdleIconLeftImage = null;
            this.Agregar.IdleIconRightImage = null;
            this.Agregar.IndicateFocus = false;
            this.Agregar.Location = new System.Drawing.Point(566, 89);
            this.Agregar.Name = "Agregar";
            this.Agregar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Agregar.OnDisabledState.BorderRadius = 20;
            this.Agregar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Agregar.OnDisabledState.BorderThickness = 1;
            this.Agregar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Agregar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Agregar.OnDisabledState.IconLeftImage = null;
            this.Agregar.OnDisabledState.IconRightImage = null;
            this.Agregar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Agregar.onHoverState.BorderRadius = 20;
            this.Agregar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Agregar.onHoverState.BorderThickness = 1;
            this.Agregar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Agregar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Agregar.onHoverState.IconLeftImage = null;
            this.Agregar.onHoverState.IconRightImage = null;
            this.Agregar.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.Agregar.OnIdleState.BorderRadius = 20;
            this.Agregar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Agregar.OnIdleState.BorderThickness = 1;
            this.Agregar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(197)))), ((int)(((byte)(18)))), ((int)(((byte)(48)))));
            this.Agregar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Agregar.OnIdleState.IconLeftImage = null;
            this.Agregar.OnIdleState.IconRightImage = null;
            this.Agregar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Agregar.OnPressedState.BorderRadius = 20;
            this.Agregar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.Agregar.OnPressedState.BorderThickness = 1;
            this.Agregar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Agregar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Agregar.OnPressedState.IconLeftImage = null;
            this.Agregar.OnPressedState.IconRightImage = null;
            this.Agregar.Size = new System.Drawing.Size(68, 32);
            this.Agregar.TabIndex = 16;
            this.Agregar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Agregar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Agregar.TextMarginLeft = 0;
            this.Agregar.TextPadding = new System.Windows.Forms.Padding(0);
            this.Agregar.UseDefaultRadiusAndThickness = true;
            // 
            // AgregarUsuario
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(650, 574);
            this.Controls.Add(this.txtsalario);
            this.Controls.Add(this.btnActualizar);
            this.Controls.Add(this.cmbCargo);
            this.Controls.Add(this.txtHijos);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.bunifuLabel16);
            this.Controls.Add(this.bunifuLabel15);
            this.Controls.Add(this.DPfechafinA);
            this.Controls.Add(this.DPfechainicioA);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.mskDUI);
            this.Controls.Add(this.dpNacimientoA);
            this.Controls.Add(this.txtCorreoA);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.txtDireccionA);
            this.Controls.Add(this.txtTelefonoA);
            this.Controls.Add(this.txtCuentabA);
            this.Controls.Add(this.txtApellidoA);
            this.Controls.Add(this.txtnombreA);
            this.Controls.Add(this.txtCodigoeA);
            this.Controls.Add(this.bunifuLabel13);
            this.Controls.Add(this.bunifuLabel12);
            this.Controls.Add(this.bunifuLabel11);
            this.Controls.Add(this.bunifuLabel10);
            this.Controls.Add(this.bunifuLabel8);
            this.Controls.Add(this.bunifuLabel7);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.bunifuLabel14);
            this.Controls.Add(this.Agregar);
            this.Controls.Add(this.label1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.Name = "AgregarUsuario";
            this.Text = "AgregarUsuario";
            this.Load += new System.EventHandler(this.AgregarUsuario_Load);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        public System.Windows.Forms.Label label1;
        public System.Windows.Forms.Label label10;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 Agregar;
        public System.Windows.Forms.MaskedTextBox mskDUI;
        public Bunifu.UI.WinForms.BunifuDatePicker dpNacimientoA;
        public Bunifu.UI.WinForms.BunifuTextBox txtCorreoA;
        public Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        public Bunifu.UI.WinForms.BunifuTextBox txtDireccionA;
        public Bunifu.UI.WinForms.BunifuTextBox txtTelefonoA;
        public Bunifu.UI.WinForms.BunifuTextBox txtCuentabA;
        public Bunifu.UI.WinForms.BunifuTextBox txtApellidoA;
        public Bunifu.UI.WinForms.BunifuTextBox txtnombreA;
        public Bunifu.UI.WinForms.BunifuTextBox txtCodigoeA;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel13;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel12;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel11;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel10;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel14;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel16;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel15;
        public Bunifu.UI.WinForms.BunifuDatePicker DPfechafinA;
        public Bunifu.UI.WinForms.BunifuDatePicker DPfechainicioA;
        public Bunifu.UI.WinForms.BunifuTextBox txtHijos;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnActualizar;
        public System.Windows.Forms.ComboBox cmbCargo;
        public Bunifu.UI.WinForms.BunifuTextBox txtsalario;
    }
}