namespace Sushi_Time_PTC_2024.Vista.Ver_Empleados
{
    partial class AgrergarEmpleado
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AgrergarEmpleado));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.btnAgregarNuevoEmpleado = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel9 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel10 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel11 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel12 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel13 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel14 = new Bunifu.UI.WinForms.BunifuLabel();
            this.txtCodigoEmpleado = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtNombreEmpleado = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtApellidosEmpleados = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtNumeroDUI = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtNumeroTelefono = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtCuentaBancaria = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtCargoEmpresa = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtSalario = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtDireccion = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtNumISSS = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtNumeroAFP = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuDatePicker1 = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.bunifuPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // btnAgregarNuevoEmpleado
            // 
            this.btnAgregarNuevoEmpleado.AllowAnimations = true;
            this.btnAgregarNuevoEmpleado.AllowMouseEffects = true;
            this.btnAgregarNuevoEmpleado.AllowToggling = false;
            this.btnAgregarNuevoEmpleado.AnimationSpeed = 200;
            this.btnAgregarNuevoEmpleado.AutoGenerateColors = false;
            this.btnAgregarNuevoEmpleado.AutoRoundBorders = false;
            this.btnAgregarNuevoEmpleado.AutoSizeLeftIcon = true;
            this.btnAgregarNuevoEmpleado.AutoSizeRightIcon = true;
            this.btnAgregarNuevoEmpleado.BackColor = System.Drawing.Color.Transparent;
            this.btnAgregarNuevoEmpleado.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(197)))), ((int)(((byte)(18)))), ((int)(((byte)(48)))));
            this.btnAgregarNuevoEmpleado.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAgregarNuevoEmpleado.BackgroundImage")));
            this.btnAgregarNuevoEmpleado.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgregarNuevoEmpleado.ButtonText = "Agrergar ";
            this.btnAgregarNuevoEmpleado.ButtonTextMarginLeft = 0;
            this.btnAgregarNuevoEmpleado.ColorContrastOnClick = 45;
            this.btnAgregarNuevoEmpleado.ColorContrastOnHover = 45;
            this.btnAgregarNuevoEmpleado.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnAgregarNuevoEmpleado.CustomizableEdges = borderEdges1;
            this.btnAgregarNuevoEmpleado.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAgregarNuevoEmpleado.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAgregarNuevoEmpleado.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAgregarNuevoEmpleado.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAgregarNuevoEmpleado.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnAgregarNuevoEmpleado.Font = new System.Drawing.Font("Yu Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAgregarNuevoEmpleado.ForeColor = System.Drawing.Color.White;
            this.btnAgregarNuevoEmpleado.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAgregarNuevoEmpleado.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAgregarNuevoEmpleado.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAgregarNuevoEmpleado.IconMarginLeft = 11;
            this.btnAgregarNuevoEmpleado.IconPadding = 10;
            this.btnAgregarNuevoEmpleado.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAgregarNuevoEmpleado.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAgregarNuevoEmpleado.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAgregarNuevoEmpleado.IconSize = 25;
            this.btnAgregarNuevoEmpleado.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnAgregarNuevoEmpleado.IdleBorderRadius = 20;
            this.btnAgregarNuevoEmpleado.IdleBorderThickness = 1;
            this.btnAgregarNuevoEmpleado.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(197)))), ((int)(((byte)(18)))), ((int)(((byte)(48)))));
            this.btnAgregarNuevoEmpleado.IdleIconLeftImage = null;
            this.btnAgregarNuevoEmpleado.IdleIconRightImage = null;
            this.btnAgregarNuevoEmpleado.IndicateFocus = false;
            this.btnAgregarNuevoEmpleado.Location = new System.Drawing.Point(989, 519);
            this.btnAgregarNuevoEmpleado.Name = "btnAgregarNuevoEmpleado";
            this.btnAgregarNuevoEmpleado.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAgregarNuevoEmpleado.OnDisabledState.BorderRadius = 20;
            this.btnAgregarNuevoEmpleado.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgregarNuevoEmpleado.OnDisabledState.BorderThickness = 1;
            this.btnAgregarNuevoEmpleado.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAgregarNuevoEmpleado.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAgregarNuevoEmpleado.OnDisabledState.IconLeftImage = null;
            this.btnAgregarNuevoEmpleado.OnDisabledState.IconRightImage = null;
            this.btnAgregarNuevoEmpleado.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAgregarNuevoEmpleado.onHoverState.BorderRadius = 20;
            this.btnAgregarNuevoEmpleado.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgregarNuevoEmpleado.onHoverState.BorderThickness = 1;
            this.btnAgregarNuevoEmpleado.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAgregarNuevoEmpleado.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAgregarNuevoEmpleado.onHoverState.IconLeftImage = null;
            this.btnAgregarNuevoEmpleado.onHoverState.IconRightImage = null;
            this.btnAgregarNuevoEmpleado.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnAgregarNuevoEmpleado.OnIdleState.BorderRadius = 20;
            this.btnAgregarNuevoEmpleado.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgregarNuevoEmpleado.OnIdleState.BorderThickness = 1;
            this.btnAgregarNuevoEmpleado.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(197)))), ((int)(((byte)(18)))), ((int)(((byte)(48)))));
            this.btnAgregarNuevoEmpleado.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAgregarNuevoEmpleado.OnIdleState.IconLeftImage = null;
            this.btnAgregarNuevoEmpleado.OnIdleState.IconRightImage = null;
            this.btnAgregarNuevoEmpleado.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAgregarNuevoEmpleado.OnPressedState.BorderRadius = 20;
            this.btnAgregarNuevoEmpleado.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAgregarNuevoEmpleado.OnPressedState.BorderThickness = 1;
            this.btnAgregarNuevoEmpleado.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAgregarNuevoEmpleado.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAgregarNuevoEmpleado.OnPressedState.IconLeftImage = null;
            this.btnAgregarNuevoEmpleado.OnPressedState.IconRightImage = null;
            this.btnAgregarNuevoEmpleado.Size = new System.Drawing.Size(174, 52);
            this.btnAgregarNuevoEmpleado.TabIndex = 9;
            this.btnAgregarNuevoEmpleado.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAgregarNuevoEmpleado.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAgregarNuevoEmpleado.TextMarginLeft = 0;
            this.btnAgregarNuevoEmpleado.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAgregarNuevoEmpleado.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(41)))), ((int)(((byte)(41)))), ((int)(((byte)(41)))));
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuPanel1.Location = new System.Drawing.Point(-8, -4);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(1215, 125);
            this.bunifuPanel1.TabIndex = 0;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Yu Gothic", 16F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(378, 42);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(466, 42);
            this.bunifuLabel1.TabIndex = 0;
            this.bunifuLabel1.Text = "Administración de Empleados";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Yu Gothic", 16F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel2.Location = new System.Drawing.Point(411, 42);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(398, 42);
            this.bunifuLabel2.TabIndex = 1;
            this.bunifuLabel2.Text = "Agregar Nuevo Empleado";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Yu Gothic UI", 10F);
            this.bunifuLabel3.Location = new System.Drawing.Point(45, 141);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(190, 28);
            this.bunifuLabel3.TabIndex = 10;
            this.bunifuLabel3.Text = "Codigo del Empleado";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Yu Gothic UI", 10F);
            this.bunifuLabel4.Location = new System.Drawing.Point(450, 141);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(81, 28);
            this.bunifuLabel4.TabIndex = 11;
            this.bunifuLabel4.Text = "Nombres";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Yu Gothic UI", 10F);
            this.bunifuLabel5.Location = new System.Drawing.Point(852, 141);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(82, 28);
            this.bunifuLabel5.TabIndex = 12;
            this.bunifuLabel5.Text = "Apellidos";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Yu Gothic UI", 10F);
            this.bunifuLabel6.Location = new System.Drawing.Point(45, 231);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(167, 28);
            this.bunifuLabel6.TabIndex = 13;
            this.bunifuLabel6.Text = "N° Cuenta Bancaria";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Yu Gothic UI", 10F);
            this.bunifuLabel7.Location = new System.Drawing.Point(455, 231);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(104, 28);
            this.bunifuLabel7.TabIndex = 14;
            this.bunifuLabel7.Text = "N° Teléfono";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Yu Gothic UI", 10F);
            this.bunifuLabel8.Location = new System.Drawing.Point(852, 231);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(61, 28);
            this.bunifuLabel8.TabIndex = 15;
            this.bunifuLabel8.Text = "N° DUI";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel9
            // 
            this.bunifuLabel9.AllowParentOverrides = false;
            this.bunifuLabel9.AutoEllipsis = false;
            this.bunifuLabel9.CursorType = null;
            this.bunifuLabel9.Font = new System.Drawing.Font("Yu Gothic UI", 10F);
            this.bunifuLabel9.Location = new System.Drawing.Point(45, 321);
            this.bunifuLabel9.Name = "bunifuLabel9";
            this.bunifuLabel9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel9.Size = new System.Drawing.Size(211, 28);
            this.bunifuLabel9.TabIndex = 16;
            this.bunifuLabel9.Text = "N° Fecha de Nacimiento";
            this.bunifuLabel9.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel9.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel10
            // 
            this.bunifuLabel10.AllowParentOverrides = false;
            this.bunifuLabel10.AutoEllipsis = false;
            this.bunifuLabel10.CursorType = null;
            this.bunifuLabel10.Font = new System.Drawing.Font("Yu Gothic UI", 10F);
            this.bunifuLabel10.Location = new System.Drawing.Point(455, 321);
            this.bunifuLabel10.Name = "bunifuLabel10";
            this.bunifuLabel10.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel10.Size = new System.Drawing.Size(60, 28);
            this.bunifuLabel10.TabIndex = 17;
            this.bunifuLabel10.Text = "Salario";
            this.bunifuLabel10.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel10.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel10.Click += new System.EventHandler(this.bunifuLabel10_Click);
            // 
            // bunifuLabel11
            // 
            this.bunifuLabel11.AllowParentOverrides = false;
            this.bunifuLabel11.AutoEllipsis = false;
            this.bunifuLabel11.CursorType = null;
            this.bunifuLabel11.Font = new System.Drawing.Font("Yu Gothic UI", 10F);
            this.bunifuLabel11.Location = new System.Drawing.Point(852, 321);
            this.bunifuLabel11.Name = "bunifuLabel11";
            this.bunifuLabel11.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel11.Size = new System.Drawing.Size(178, 28);
            this.bunifuLabel11.TabIndex = 18;
            this.bunifuLabel11.Text = "Cargo en la Empresa";
            this.bunifuLabel11.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel11.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel12
            // 
            this.bunifuLabel12.AllowParentOverrides = false;
            this.bunifuLabel12.AutoEllipsis = false;
            this.bunifuLabel12.CursorType = null;
            this.bunifuLabel12.Font = new System.Drawing.Font("Yu Gothic UI", 10F);
            this.bunifuLabel12.Location = new System.Drawing.Point(48, 411);
            this.bunifuLabel12.Name = "bunifuLabel12";
            this.bunifuLabel12.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel12.Size = new System.Drawing.Size(62, 28);
            this.bunifuLabel12.TabIndex = 19;
            this.bunifuLabel12.Text = "N° AFP ";
            this.bunifuLabel12.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel12.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel13
            // 
            this.bunifuLabel13.AllowParentOverrides = false;
            this.bunifuLabel13.AutoEllipsis = false;
            this.bunifuLabel13.CursorType = null;
            this.bunifuLabel13.Font = new System.Drawing.Font("Yu Gothic UI", 10F);
            this.bunifuLabel13.Location = new System.Drawing.Point(455, 411);
            this.bunifuLabel13.Name = "bunifuLabel13";
            this.bunifuLabel13.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel13.Size = new System.Drawing.Size(66, 28);
            this.bunifuLabel13.TabIndex = 20;
            this.bunifuLabel13.Text = "N° ISSS";
            this.bunifuLabel13.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel13.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel14
            // 
            this.bunifuLabel14.AllowParentOverrides = false;
            this.bunifuLabel14.AutoEllipsis = false;
            this.bunifuLabel14.CursorType = null;
            this.bunifuLabel14.Font = new System.Drawing.Font("Yu Gothic UI", 10F);
            this.bunifuLabel14.Location = new System.Drawing.Point(852, 411);
            this.bunifuLabel14.Name = "bunifuLabel14";
            this.bunifuLabel14.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel14.Size = new System.Drawing.Size(82, 28);
            this.bunifuLabel14.TabIndex = 21;
            this.bunifuLabel14.Text = "Dirección";
            this.bunifuLabel14.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel14.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // txtCodigoEmpleado
            // 
            this.txtCodigoEmpleado.AcceptsReturn = false;
            this.txtCodigoEmpleado.AcceptsTab = false;
            this.txtCodigoEmpleado.AnimationSpeed = 200;
            this.txtCodigoEmpleado.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCodigoEmpleado.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCodigoEmpleado.AutoSizeHeight = true;
            this.txtCodigoEmpleado.BackColor = System.Drawing.Color.Transparent;
            this.txtCodigoEmpleado.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCodigoEmpleado.BackgroundImage")));
            this.txtCodigoEmpleado.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCodigoEmpleado.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCodigoEmpleado.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCodigoEmpleado.BorderColorIdle = System.Drawing.Color.Black;
            this.txtCodigoEmpleado.BorderRadius = 20;
            this.txtCodigoEmpleado.BorderThickness = 1;
            this.txtCodigoEmpleado.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCodigoEmpleado.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCodigoEmpleado.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCodigoEmpleado.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCodigoEmpleado.DefaultText = "";
            this.txtCodigoEmpleado.FillColor = System.Drawing.Color.White;
            this.txtCodigoEmpleado.HideSelection = true;
            this.txtCodigoEmpleado.IconLeft = null;
            this.txtCodigoEmpleado.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCodigoEmpleado.IconPadding = 10;
            this.txtCodigoEmpleado.IconRight = null;
            this.txtCodigoEmpleado.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCodigoEmpleado.Lines = new string[0];
            this.txtCodigoEmpleado.Location = new System.Drawing.Point(45, 175);
            this.txtCodigoEmpleado.MaxLength = 32767;
            this.txtCodigoEmpleado.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCodigoEmpleado.Modified = false;
            this.txtCodigoEmpleado.Multiline = false;
            this.txtCodigoEmpleado.Name = "txtCodigoEmpleado";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCodigoEmpleado.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCodigoEmpleado.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCodigoEmpleado.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Black;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCodigoEmpleado.OnIdleState = stateProperties4;
            this.txtCodigoEmpleado.Padding = new System.Windows.Forms.Padding(3);
            this.txtCodigoEmpleado.PasswordChar = '\0';
            this.txtCodigoEmpleado.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCodigoEmpleado.PlaceholderText = "";
            this.txtCodigoEmpleado.ReadOnly = false;
            this.txtCodigoEmpleado.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCodigoEmpleado.SelectedText = "";
            this.txtCodigoEmpleado.SelectionLength = 0;
            this.txtCodigoEmpleado.SelectionStart = 0;
            this.txtCodigoEmpleado.ShortcutsEnabled = true;
            this.txtCodigoEmpleado.Size = new System.Drawing.Size(316, 50);
            this.txtCodigoEmpleado.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCodigoEmpleado.TabIndex = 22;
            this.txtCodigoEmpleado.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCodigoEmpleado.TextMarginBottom = 0;
            this.txtCodigoEmpleado.TextMarginLeft = 3;
            this.txtCodigoEmpleado.TextMarginTop = 1;
            this.txtCodigoEmpleado.TextPlaceholder = "";
            this.txtCodigoEmpleado.UseSystemPasswordChar = false;
            this.txtCodigoEmpleado.WordWrap = true;
            // 
            // txtNombreEmpleado
            // 
            this.txtNombreEmpleado.AcceptsReturn = false;
            this.txtNombreEmpleado.AcceptsTab = false;
            this.txtNombreEmpleado.AnimationSpeed = 200;
            this.txtNombreEmpleado.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNombreEmpleado.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNombreEmpleado.AutoSizeHeight = true;
            this.txtNombreEmpleado.BackColor = System.Drawing.Color.Transparent;
            this.txtNombreEmpleado.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNombreEmpleado.BackgroundImage")));
            this.txtNombreEmpleado.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNombreEmpleado.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNombreEmpleado.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNombreEmpleado.BorderColorIdle = System.Drawing.Color.Black;
            this.txtNombreEmpleado.BorderRadius = 20;
            this.txtNombreEmpleado.BorderThickness = 1;
            this.txtNombreEmpleado.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtNombreEmpleado.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNombreEmpleado.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombreEmpleado.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtNombreEmpleado.DefaultText = "";
            this.txtNombreEmpleado.FillColor = System.Drawing.Color.White;
            this.txtNombreEmpleado.HideSelection = true;
            this.txtNombreEmpleado.IconLeft = null;
            this.txtNombreEmpleado.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombreEmpleado.IconPadding = 10;
            this.txtNombreEmpleado.IconRight = null;
            this.txtNombreEmpleado.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNombreEmpleado.Lines = new string[0];
            this.txtNombreEmpleado.Location = new System.Drawing.Point(450, 175);
            this.txtNombreEmpleado.MaxLength = 32767;
            this.txtNombreEmpleado.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNombreEmpleado.Modified = false;
            this.txtNombreEmpleado.Multiline = false;
            this.txtNombreEmpleado.Name = "txtNombreEmpleado";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombreEmpleado.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNombreEmpleado.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombreEmpleado.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Black;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNombreEmpleado.OnIdleState = stateProperties8;
            this.txtNombreEmpleado.Padding = new System.Windows.Forms.Padding(3);
            this.txtNombreEmpleado.PasswordChar = '\0';
            this.txtNombreEmpleado.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNombreEmpleado.PlaceholderText = "";
            this.txtNombreEmpleado.ReadOnly = false;
            this.txtNombreEmpleado.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNombreEmpleado.SelectedText = "";
            this.txtNombreEmpleado.SelectionLength = 0;
            this.txtNombreEmpleado.SelectionStart = 0;
            this.txtNombreEmpleado.ShortcutsEnabled = true;
            this.txtNombreEmpleado.Size = new System.Drawing.Size(316, 50);
            this.txtNombreEmpleado.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNombreEmpleado.TabIndex = 23;
            this.txtNombreEmpleado.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNombreEmpleado.TextMarginBottom = 0;
            this.txtNombreEmpleado.TextMarginLeft = 3;
            this.txtNombreEmpleado.TextMarginTop = 1;
            this.txtNombreEmpleado.TextPlaceholder = "";
            this.txtNombreEmpleado.UseSystemPasswordChar = false;
            this.txtNombreEmpleado.WordWrap = true;
            // 
            // txtApellidosEmpleados
            // 
            this.txtApellidosEmpleados.AcceptsReturn = false;
            this.txtApellidosEmpleados.AcceptsTab = false;
            this.txtApellidosEmpleados.AnimationSpeed = 200;
            this.txtApellidosEmpleados.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtApellidosEmpleados.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtApellidosEmpleados.AutoSizeHeight = true;
            this.txtApellidosEmpleados.BackColor = System.Drawing.Color.Transparent;
            this.txtApellidosEmpleados.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtApellidosEmpleados.BackgroundImage")));
            this.txtApellidosEmpleados.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtApellidosEmpleados.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtApellidosEmpleados.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtApellidosEmpleados.BorderColorIdle = System.Drawing.Color.Black;
            this.txtApellidosEmpleados.BorderRadius = 20;
            this.txtApellidosEmpleados.BorderThickness = 1;
            this.txtApellidosEmpleados.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtApellidosEmpleados.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtApellidosEmpleados.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtApellidosEmpleados.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtApellidosEmpleados.DefaultText = "";
            this.txtApellidosEmpleados.FillColor = System.Drawing.Color.White;
            this.txtApellidosEmpleados.HideSelection = true;
            this.txtApellidosEmpleados.IconLeft = null;
            this.txtApellidosEmpleados.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtApellidosEmpleados.IconPadding = 10;
            this.txtApellidosEmpleados.IconRight = null;
            this.txtApellidosEmpleados.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtApellidosEmpleados.Lines = new string[0];
            this.txtApellidosEmpleados.Location = new System.Drawing.Point(847, 175);
            this.txtApellidosEmpleados.MaxLength = 32767;
            this.txtApellidosEmpleados.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtApellidosEmpleados.Modified = false;
            this.txtApellidosEmpleados.Multiline = false;
            this.txtApellidosEmpleados.Name = "txtApellidosEmpleados";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtApellidosEmpleados.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtApellidosEmpleados.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtApellidosEmpleados.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Black;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtApellidosEmpleados.OnIdleState = stateProperties12;
            this.txtApellidosEmpleados.Padding = new System.Windows.Forms.Padding(3);
            this.txtApellidosEmpleados.PasswordChar = '\0';
            this.txtApellidosEmpleados.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtApellidosEmpleados.PlaceholderText = "";
            this.txtApellidosEmpleados.ReadOnly = false;
            this.txtApellidosEmpleados.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtApellidosEmpleados.SelectedText = "";
            this.txtApellidosEmpleados.SelectionLength = 0;
            this.txtApellidosEmpleados.SelectionStart = 0;
            this.txtApellidosEmpleados.ShortcutsEnabled = true;
            this.txtApellidosEmpleados.Size = new System.Drawing.Size(316, 50);
            this.txtApellidosEmpleados.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtApellidosEmpleados.TabIndex = 24;
            this.txtApellidosEmpleados.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtApellidosEmpleados.TextMarginBottom = 0;
            this.txtApellidosEmpleados.TextMarginLeft = 3;
            this.txtApellidosEmpleados.TextMarginTop = 1;
            this.txtApellidosEmpleados.TextPlaceholder = "";
            this.txtApellidosEmpleados.UseSystemPasswordChar = false;
            this.txtApellidosEmpleados.WordWrap = true;
            // 
            // txtNumeroDUI
            // 
            this.txtNumeroDUI.AcceptsReturn = false;
            this.txtNumeroDUI.AcceptsTab = false;
            this.txtNumeroDUI.AnimationSpeed = 200;
            this.txtNumeroDUI.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNumeroDUI.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNumeroDUI.AutoSizeHeight = true;
            this.txtNumeroDUI.BackColor = System.Drawing.Color.Transparent;
            this.txtNumeroDUI.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNumeroDUI.BackgroundImage")));
            this.txtNumeroDUI.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNumeroDUI.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNumeroDUI.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNumeroDUI.BorderColorIdle = System.Drawing.Color.Black;
            this.txtNumeroDUI.BorderRadius = 20;
            this.txtNumeroDUI.BorderThickness = 1;
            this.txtNumeroDUI.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtNumeroDUI.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNumeroDUI.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNumeroDUI.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtNumeroDUI.DefaultText = "";
            this.txtNumeroDUI.FillColor = System.Drawing.Color.White;
            this.txtNumeroDUI.HideSelection = true;
            this.txtNumeroDUI.IconLeft = null;
            this.txtNumeroDUI.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNumeroDUI.IconPadding = 10;
            this.txtNumeroDUI.IconRight = null;
            this.txtNumeroDUI.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNumeroDUI.Lines = new string[0];
            this.txtNumeroDUI.Location = new System.Drawing.Point(847, 265);
            this.txtNumeroDUI.MaxLength = 32767;
            this.txtNumeroDUI.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNumeroDUI.Modified = false;
            this.txtNumeroDUI.Multiline = false;
            this.txtNumeroDUI.Name = "txtNumeroDUI";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNumeroDUI.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNumeroDUI.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNumeroDUI.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Black;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNumeroDUI.OnIdleState = stateProperties16;
            this.txtNumeroDUI.Padding = new System.Windows.Forms.Padding(3);
            this.txtNumeroDUI.PasswordChar = '\0';
            this.txtNumeroDUI.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNumeroDUI.PlaceholderText = "";
            this.txtNumeroDUI.ReadOnly = false;
            this.txtNumeroDUI.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNumeroDUI.SelectedText = "";
            this.txtNumeroDUI.SelectionLength = 0;
            this.txtNumeroDUI.SelectionStart = 0;
            this.txtNumeroDUI.ShortcutsEnabled = true;
            this.txtNumeroDUI.Size = new System.Drawing.Size(316, 50);
            this.txtNumeroDUI.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNumeroDUI.TabIndex = 27;
            this.txtNumeroDUI.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNumeroDUI.TextMarginBottom = 0;
            this.txtNumeroDUI.TextMarginLeft = 3;
            this.txtNumeroDUI.TextMarginTop = 1;
            this.txtNumeroDUI.TextPlaceholder = "";
            this.txtNumeroDUI.UseSystemPasswordChar = false;
            this.txtNumeroDUI.WordWrap = true;
            // 
            // txtNumeroTelefono
            // 
            this.txtNumeroTelefono.AcceptsReturn = false;
            this.txtNumeroTelefono.AcceptsTab = false;
            this.txtNumeroTelefono.AnimationSpeed = 200;
            this.txtNumeroTelefono.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNumeroTelefono.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNumeroTelefono.AutoSizeHeight = true;
            this.txtNumeroTelefono.BackColor = System.Drawing.Color.Transparent;
            this.txtNumeroTelefono.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNumeroTelefono.BackgroundImage")));
            this.txtNumeroTelefono.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNumeroTelefono.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNumeroTelefono.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNumeroTelefono.BorderColorIdle = System.Drawing.Color.Black;
            this.txtNumeroTelefono.BorderRadius = 20;
            this.txtNumeroTelefono.BorderThickness = 1;
            this.txtNumeroTelefono.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtNumeroTelefono.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNumeroTelefono.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNumeroTelefono.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtNumeroTelefono.DefaultText = "";
            this.txtNumeroTelefono.FillColor = System.Drawing.Color.White;
            this.txtNumeroTelefono.HideSelection = true;
            this.txtNumeroTelefono.IconLeft = null;
            this.txtNumeroTelefono.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNumeroTelefono.IconPadding = 10;
            this.txtNumeroTelefono.IconRight = null;
            this.txtNumeroTelefono.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNumeroTelefono.Lines = new string[0];
            this.txtNumeroTelefono.Location = new System.Drawing.Point(450, 265);
            this.txtNumeroTelefono.MaxLength = 32767;
            this.txtNumeroTelefono.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNumeroTelefono.Modified = false;
            this.txtNumeroTelefono.Multiline = false;
            this.txtNumeroTelefono.Name = "txtNumeroTelefono";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNumeroTelefono.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNumeroTelefono.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNumeroTelefono.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Black;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNumeroTelefono.OnIdleState = stateProperties20;
            this.txtNumeroTelefono.Padding = new System.Windows.Forms.Padding(3);
            this.txtNumeroTelefono.PasswordChar = '\0';
            this.txtNumeroTelefono.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNumeroTelefono.PlaceholderText = "";
            this.txtNumeroTelefono.ReadOnly = false;
            this.txtNumeroTelefono.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNumeroTelefono.SelectedText = "";
            this.txtNumeroTelefono.SelectionLength = 0;
            this.txtNumeroTelefono.SelectionStart = 0;
            this.txtNumeroTelefono.ShortcutsEnabled = true;
            this.txtNumeroTelefono.Size = new System.Drawing.Size(316, 50);
            this.txtNumeroTelefono.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNumeroTelefono.TabIndex = 26;
            this.txtNumeroTelefono.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNumeroTelefono.TextMarginBottom = 0;
            this.txtNumeroTelefono.TextMarginLeft = 3;
            this.txtNumeroTelefono.TextMarginTop = 1;
            this.txtNumeroTelefono.TextPlaceholder = "";
            this.txtNumeroTelefono.UseSystemPasswordChar = false;
            this.txtNumeroTelefono.WordWrap = true;
            // 
            // txtCuentaBancaria
            // 
            this.txtCuentaBancaria.AcceptsReturn = false;
            this.txtCuentaBancaria.AcceptsTab = false;
            this.txtCuentaBancaria.AnimationSpeed = 200;
            this.txtCuentaBancaria.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCuentaBancaria.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCuentaBancaria.AutoSizeHeight = true;
            this.txtCuentaBancaria.BackColor = System.Drawing.Color.Transparent;
            this.txtCuentaBancaria.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCuentaBancaria.BackgroundImage")));
            this.txtCuentaBancaria.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCuentaBancaria.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCuentaBancaria.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCuentaBancaria.BorderColorIdle = System.Drawing.Color.Black;
            this.txtCuentaBancaria.BorderRadius = 20;
            this.txtCuentaBancaria.BorderThickness = 1;
            this.txtCuentaBancaria.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCuentaBancaria.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCuentaBancaria.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCuentaBancaria.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCuentaBancaria.DefaultText = "";
            this.txtCuentaBancaria.FillColor = System.Drawing.Color.White;
            this.txtCuentaBancaria.HideSelection = true;
            this.txtCuentaBancaria.IconLeft = null;
            this.txtCuentaBancaria.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCuentaBancaria.IconPadding = 10;
            this.txtCuentaBancaria.IconRight = null;
            this.txtCuentaBancaria.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCuentaBancaria.Lines = new string[0];
            this.txtCuentaBancaria.Location = new System.Drawing.Point(45, 265);
            this.txtCuentaBancaria.MaxLength = 32767;
            this.txtCuentaBancaria.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCuentaBancaria.Modified = false;
            this.txtCuentaBancaria.Multiline = false;
            this.txtCuentaBancaria.Name = "txtCuentaBancaria";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCuentaBancaria.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCuentaBancaria.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCuentaBancaria.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Black;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCuentaBancaria.OnIdleState = stateProperties24;
            this.txtCuentaBancaria.Padding = new System.Windows.Forms.Padding(3);
            this.txtCuentaBancaria.PasswordChar = '\0';
            this.txtCuentaBancaria.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCuentaBancaria.PlaceholderText = "";
            this.txtCuentaBancaria.ReadOnly = false;
            this.txtCuentaBancaria.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCuentaBancaria.SelectedText = "";
            this.txtCuentaBancaria.SelectionLength = 0;
            this.txtCuentaBancaria.SelectionStart = 0;
            this.txtCuentaBancaria.ShortcutsEnabled = true;
            this.txtCuentaBancaria.Size = new System.Drawing.Size(316, 50);
            this.txtCuentaBancaria.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCuentaBancaria.TabIndex = 25;
            this.txtCuentaBancaria.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCuentaBancaria.TextMarginBottom = 0;
            this.txtCuentaBancaria.TextMarginLeft = 3;
            this.txtCuentaBancaria.TextMarginTop = 1;
            this.txtCuentaBancaria.TextPlaceholder = "";
            this.txtCuentaBancaria.UseSystemPasswordChar = false;
            this.txtCuentaBancaria.WordWrap = true;
            // 
            // txtCargoEmpresa
            // 
            this.txtCargoEmpresa.AcceptsReturn = false;
            this.txtCargoEmpresa.AcceptsTab = false;
            this.txtCargoEmpresa.AnimationSpeed = 200;
            this.txtCargoEmpresa.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtCargoEmpresa.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtCargoEmpresa.AutoSizeHeight = true;
            this.txtCargoEmpresa.BackColor = System.Drawing.Color.Transparent;
            this.txtCargoEmpresa.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtCargoEmpresa.BackgroundImage")));
            this.txtCargoEmpresa.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtCargoEmpresa.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtCargoEmpresa.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtCargoEmpresa.BorderColorIdle = System.Drawing.Color.Black;
            this.txtCargoEmpresa.BorderRadius = 20;
            this.txtCargoEmpresa.BorderThickness = 1;
            this.txtCargoEmpresa.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtCargoEmpresa.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtCargoEmpresa.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCargoEmpresa.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtCargoEmpresa.DefaultText = "";
            this.txtCargoEmpresa.FillColor = System.Drawing.Color.White;
            this.txtCargoEmpresa.HideSelection = true;
            this.txtCargoEmpresa.IconLeft = null;
            this.txtCargoEmpresa.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCargoEmpresa.IconPadding = 10;
            this.txtCargoEmpresa.IconRight = null;
            this.txtCargoEmpresa.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtCargoEmpresa.Lines = new string[0];
            this.txtCargoEmpresa.Location = new System.Drawing.Point(847, 355);
            this.txtCargoEmpresa.MaxLength = 32767;
            this.txtCargoEmpresa.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtCargoEmpresa.Modified = false;
            this.txtCargoEmpresa.Multiline = false;
            this.txtCargoEmpresa.Name = "txtCargoEmpresa";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCargoEmpresa.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtCargoEmpresa.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCargoEmpresa.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Black;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtCargoEmpresa.OnIdleState = stateProperties28;
            this.txtCargoEmpresa.Padding = new System.Windows.Forms.Padding(3);
            this.txtCargoEmpresa.PasswordChar = '\0';
            this.txtCargoEmpresa.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtCargoEmpresa.PlaceholderText = "";
            this.txtCargoEmpresa.ReadOnly = false;
            this.txtCargoEmpresa.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtCargoEmpresa.SelectedText = "";
            this.txtCargoEmpresa.SelectionLength = 0;
            this.txtCargoEmpresa.SelectionStart = 0;
            this.txtCargoEmpresa.ShortcutsEnabled = true;
            this.txtCargoEmpresa.Size = new System.Drawing.Size(316, 50);
            this.txtCargoEmpresa.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtCargoEmpresa.TabIndex = 30;
            this.txtCargoEmpresa.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtCargoEmpresa.TextMarginBottom = 0;
            this.txtCargoEmpresa.TextMarginLeft = 3;
            this.txtCargoEmpresa.TextMarginTop = 1;
            this.txtCargoEmpresa.TextPlaceholder = "";
            this.txtCargoEmpresa.UseSystemPasswordChar = false;
            this.txtCargoEmpresa.WordWrap = true;
            // 
            // txtSalario
            // 
            this.txtSalario.AcceptsReturn = false;
            this.txtSalario.AcceptsTab = false;
            this.txtSalario.AnimationSpeed = 200;
            this.txtSalario.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSalario.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSalario.AutoSizeHeight = true;
            this.txtSalario.BackColor = System.Drawing.Color.Transparent;
            this.txtSalario.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSalario.BackgroundImage")));
            this.txtSalario.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSalario.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSalario.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSalario.BorderColorIdle = System.Drawing.Color.Black;
            this.txtSalario.BorderRadius = 20;
            this.txtSalario.BorderThickness = 1;
            this.txtSalario.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtSalario.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSalario.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSalario.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtSalario.DefaultText = "";
            this.txtSalario.FillColor = System.Drawing.Color.White;
            this.txtSalario.HideSelection = true;
            this.txtSalario.IconLeft = null;
            this.txtSalario.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSalario.IconPadding = 10;
            this.txtSalario.IconRight = null;
            this.txtSalario.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSalario.Lines = new string[0];
            this.txtSalario.Location = new System.Drawing.Point(450, 355);
            this.txtSalario.MaxLength = 32767;
            this.txtSalario.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSalario.Modified = false;
            this.txtSalario.Multiline = false;
            this.txtSalario.Name = "txtSalario";
            stateProperties29.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSalario.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSalario.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSalario.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Black;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSalario.OnIdleState = stateProperties32;
            this.txtSalario.Padding = new System.Windows.Forms.Padding(3);
            this.txtSalario.PasswordChar = '\0';
            this.txtSalario.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtSalario.PlaceholderText = "";
            this.txtSalario.ReadOnly = false;
            this.txtSalario.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSalario.SelectedText = "";
            this.txtSalario.SelectionLength = 0;
            this.txtSalario.SelectionStart = 0;
            this.txtSalario.ShortcutsEnabled = true;
            this.txtSalario.Size = new System.Drawing.Size(316, 50);
            this.txtSalario.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSalario.TabIndex = 29;
            this.txtSalario.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSalario.TextMarginBottom = 0;
            this.txtSalario.TextMarginLeft = 3;
            this.txtSalario.TextMarginTop = 1;
            this.txtSalario.TextPlaceholder = "";
            this.txtSalario.UseSystemPasswordChar = false;
            this.txtSalario.WordWrap = true;
            // 
            // txtDireccion
            // 
            this.txtDireccion.AcceptsReturn = false;
            this.txtDireccion.AcceptsTab = false;
            this.txtDireccion.AnimationSpeed = 200;
            this.txtDireccion.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDireccion.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDireccion.AutoSizeHeight = true;
            this.txtDireccion.BackColor = System.Drawing.Color.Transparent;
            this.txtDireccion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDireccion.BackgroundImage")));
            this.txtDireccion.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDireccion.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDireccion.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDireccion.BorderColorIdle = System.Drawing.Color.Black;
            this.txtDireccion.BorderRadius = 20;
            this.txtDireccion.BorderThickness = 1;
            this.txtDireccion.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtDireccion.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDireccion.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDireccion.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDireccion.DefaultText = "";
            this.txtDireccion.FillColor = System.Drawing.Color.White;
            this.txtDireccion.HideSelection = true;
            this.txtDireccion.IconLeft = null;
            this.txtDireccion.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDireccion.IconPadding = 10;
            this.txtDireccion.IconRight = null;
            this.txtDireccion.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDireccion.Lines = new string[0];
            this.txtDireccion.Location = new System.Drawing.Point(847, 445);
            this.txtDireccion.MaxLength = 32767;
            this.txtDireccion.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDireccion.Modified = false;
            this.txtDireccion.Multiline = false;
            this.txtDireccion.Name = "txtDireccion";
            stateProperties33.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDireccion.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDireccion.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDireccion.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Black;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDireccion.OnIdleState = stateProperties36;
            this.txtDireccion.Padding = new System.Windows.Forms.Padding(3);
            this.txtDireccion.PasswordChar = '\0';
            this.txtDireccion.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDireccion.PlaceholderText = "";
            this.txtDireccion.ReadOnly = false;
            this.txtDireccion.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDireccion.SelectedText = "";
            this.txtDireccion.SelectionLength = 0;
            this.txtDireccion.SelectionStart = 0;
            this.txtDireccion.ShortcutsEnabled = true;
            this.txtDireccion.Size = new System.Drawing.Size(316, 50);
            this.txtDireccion.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDireccion.TabIndex = 33;
            this.txtDireccion.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDireccion.TextMarginBottom = 0;
            this.txtDireccion.TextMarginLeft = 3;
            this.txtDireccion.TextMarginTop = 1;
            this.txtDireccion.TextPlaceholder = "";
            this.txtDireccion.UseSystemPasswordChar = false;
            this.txtDireccion.WordWrap = true;
            // 
            // txtNumISSS
            // 
            this.txtNumISSS.AcceptsReturn = false;
            this.txtNumISSS.AcceptsTab = false;
            this.txtNumISSS.AnimationSpeed = 200;
            this.txtNumISSS.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNumISSS.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNumISSS.AutoSizeHeight = true;
            this.txtNumISSS.BackColor = System.Drawing.Color.Transparent;
            this.txtNumISSS.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNumISSS.BackgroundImage")));
            this.txtNumISSS.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNumISSS.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNumISSS.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNumISSS.BorderColorIdle = System.Drawing.Color.Black;
            this.txtNumISSS.BorderRadius = 20;
            this.txtNumISSS.BorderThickness = 1;
            this.txtNumISSS.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtNumISSS.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNumISSS.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNumISSS.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtNumISSS.DefaultText = "";
            this.txtNumISSS.FillColor = System.Drawing.Color.White;
            this.txtNumISSS.HideSelection = true;
            this.txtNumISSS.IconLeft = null;
            this.txtNumISSS.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNumISSS.IconPadding = 10;
            this.txtNumISSS.IconRight = null;
            this.txtNumISSS.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNumISSS.Lines = new string[0];
            this.txtNumISSS.Location = new System.Drawing.Point(450, 445);
            this.txtNumISSS.MaxLength = 32767;
            this.txtNumISSS.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNumISSS.Modified = false;
            this.txtNumISSS.Multiline = false;
            this.txtNumISSS.Name = "txtNumISSS";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNumISSS.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNumISSS.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNumISSS.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Black;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNumISSS.OnIdleState = stateProperties40;
            this.txtNumISSS.Padding = new System.Windows.Forms.Padding(3);
            this.txtNumISSS.PasswordChar = '\0';
            this.txtNumISSS.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNumISSS.PlaceholderText = "";
            this.txtNumISSS.ReadOnly = false;
            this.txtNumISSS.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNumISSS.SelectedText = "";
            this.txtNumISSS.SelectionLength = 0;
            this.txtNumISSS.SelectionStart = 0;
            this.txtNumISSS.ShortcutsEnabled = true;
            this.txtNumISSS.Size = new System.Drawing.Size(316, 50);
            this.txtNumISSS.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNumISSS.TabIndex = 32;
            this.txtNumISSS.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNumISSS.TextMarginBottom = 0;
            this.txtNumISSS.TextMarginLeft = 3;
            this.txtNumISSS.TextMarginTop = 1;
            this.txtNumISSS.TextPlaceholder = "";
            this.txtNumISSS.UseSystemPasswordChar = false;
            this.txtNumISSS.WordWrap = true;
            // 
            // txtNumeroAFP
            // 
            this.txtNumeroAFP.AcceptsReturn = false;
            this.txtNumeroAFP.AcceptsTab = false;
            this.txtNumeroAFP.AnimationSpeed = 200;
            this.txtNumeroAFP.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNumeroAFP.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNumeroAFP.AutoSizeHeight = true;
            this.txtNumeroAFP.BackColor = System.Drawing.Color.Transparent;
            this.txtNumeroAFP.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNumeroAFP.BackgroundImage")));
            this.txtNumeroAFP.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNumeroAFP.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNumeroAFP.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNumeroAFP.BorderColorIdle = System.Drawing.Color.Black;
            this.txtNumeroAFP.BorderRadius = 20;
            this.txtNumeroAFP.BorderThickness = 1;
            this.txtNumeroAFP.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtNumeroAFP.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNumeroAFP.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNumeroAFP.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtNumeroAFP.DefaultText = "";
            this.txtNumeroAFP.FillColor = System.Drawing.Color.White;
            this.txtNumeroAFP.HideSelection = true;
            this.txtNumeroAFP.IconLeft = null;
            this.txtNumeroAFP.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNumeroAFP.IconPadding = 10;
            this.txtNumeroAFP.IconRight = null;
            this.txtNumeroAFP.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNumeroAFP.Lines = new string[0];
            this.txtNumeroAFP.Location = new System.Drawing.Point(45, 445);
            this.txtNumeroAFP.MaxLength = 32767;
            this.txtNumeroAFP.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNumeroAFP.Modified = false;
            this.txtNumeroAFP.Multiline = false;
            this.txtNumeroAFP.Name = "txtNumeroAFP";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNumeroAFP.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNumeroAFP.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNumeroAFP.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Black;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNumeroAFP.OnIdleState = stateProperties44;
            this.txtNumeroAFP.Padding = new System.Windows.Forms.Padding(3);
            this.txtNumeroAFP.PasswordChar = '\0';
            this.txtNumeroAFP.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNumeroAFP.PlaceholderText = "";
            this.txtNumeroAFP.ReadOnly = false;
            this.txtNumeroAFP.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNumeroAFP.SelectedText = "";
            this.txtNumeroAFP.SelectionLength = 0;
            this.txtNumeroAFP.SelectionStart = 0;
            this.txtNumeroAFP.ShortcutsEnabled = true;
            this.txtNumeroAFP.Size = new System.Drawing.Size(316, 50);
            this.txtNumeroAFP.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNumeroAFP.TabIndex = 31;
            this.txtNumeroAFP.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNumeroAFP.TextMarginBottom = 0;
            this.txtNumeroAFP.TextMarginLeft = 3;
            this.txtNumeroAFP.TextMarginTop = 1;
            this.txtNumeroAFP.TextPlaceholder = "";
            this.txtNumeroAFP.UseSystemPasswordChar = false;
            this.txtNumeroAFP.WordWrap = true;
            // 
            // bunifuDatePicker1
            // 
            this.bunifuDatePicker1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuDatePicker1.BorderColor = System.Drawing.Color.Silver;
            this.bunifuDatePicker1.BorderRadius = 10;
            this.bunifuDatePicker1.Color = System.Drawing.Color.Silver;
            this.bunifuDatePicker1.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.bunifuDatePicker1.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.bunifuDatePicker1.DisabledColor = System.Drawing.Color.Gray;
            this.bunifuDatePicker1.DisplayWeekNumbers = false;
            this.bunifuDatePicker1.DPHeight = 0;
            this.bunifuDatePicker1.FillDatePicker = false;
            this.bunifuDatePicker1.Font = new System.Drawing.Font("Yu Gothic UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuDatePicker1.ForeColor = System.Drawing.Color.Black;
            this.bunifuDatePicker1.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuDatePicker1.Icon")));
            this.bunifuDatePicker1.IconColor = System.Drawing.Color.Gray;
            this.bunifuDatePicker1.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.bunifuDatePicker1.LeftTextMargin = 5;
            this.bunifuDatePicker1.Location = new System.Drawing.Point(45, 364);
            this.bunifuDatePicker1.MinimumSize = new System.Drawing.Size(0, 32);
            this.bunifuDatePicker1.Name = "bunifuDatePicker1";
            this.bunifuDatePicker1.Size = new System.Drawing.Size(316, 32);
            this.bunifuDatePicker1.TabIndex = 34;
            this.bunifuDatePicker1.Value = new System.DateTime(2024, 8, 11, 9, 44, 0, 0);
            // 
            // AgrergarEmpleado
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1206, 595);
            this.Controls.Add(this.bunifuDatePicker1);
            this.Controls.Add(this.txtDireccion);
            this.Controls.Add(this.txtNumISSS);
            this.Controls.Add(this.txtNumeroAFP);
            this.Controls.Add(this.txtCargoEmpresa);
            this.Controls.Add(this.txtSalario);
            this.Controls.Add(this.txtNumeroDUI);
            this.Controls.Add(this.txtNumeroTelefono);
            this.Controls.Add(this.txtCuentaBancaria);
            this.Controls.Add(this.txtApellidosEmpleados);
            this.Controls.Add(this.txtNombreEmpleado);
            this.Controls.Add(this.txtCodigoEmpleado);
            this.Controls.Add(this.bunifuLabel14);
            this.Controls.Add(this.bunifuLabel13);
            this.Controls.Add(this.bunifuLabel12);
            this.Controls.Add(this.bunifuLabel11);
            this.Controls.Add(this.bunifuLabel10);
            this.Controls.Add(this.bunifuLabel9);
            this.Controls.Add(this.bunifuLabel8);
            this.Controls.Add(this.bunifuLabel7);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.btnAgregarNuevoEmpleado);
            this.Controls.Add(this.bunifuPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "AgrergarEmpleado";
            this.Text = "AgrergarEmpleado";
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnAgregarNuevoEmpleado;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel9;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel10;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel11;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel12;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel13;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel14;
        private Bunifu.UI.WinForms.BunifuTextBox txtCodigoEmpleado;
        private Bunifu.UI.WinForms.BunifuTextBox txtNombreEmpleado;
        private Bunifu.UI.WinForms.BunifuTextBox txtApellidosEmpleados;
        private Bunifu.UI.WinForms.BunifuTextBox txtNumeroDUI;
        private Bunifu.UI.WinForms.BunifuTextBox txtNumeroTelefono;
        private Bunifu.UI.WinForms.BunifuTextBox txtCuentaBancaria;
        private Bunifu.UI.WinForms.BunifuTextBox txtCargoEmpresa;
        private Bunifu.UI.WinForms.BunifuTextBox txtSalario;
        private Bunifu.UI.WinForms.BunifuTextBox txtDireccion;
        private Bunifu.UI.WinForms.BunifuTextBox txtNumISSS;
        private Bunifu.UI.WinForms.BunifuTextBox txtNumeroAFP;
        private Bunifu.UI.WinForms.BunifuDatePicker bunifuDatePicker1;
    }
}